version: '3'

services:
  meican:
    env_file:
      - .env
    container_name: meican-app
    ports:
      - "${MEICAN_PORT:-80}:80"
      - "${MEICAN_PORT_HTTPS:-443}:443"
    depends_on:
      - db
    links:
      - db
    # Example on how to setup your own SSL Certificate:
    #volumes:
    #  - ./mycert.key:/etc/ssl/private/ssl-cert-snakeoil.key:ro
    #  - ./mycert.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem:ro

  db:
    image: mysql:5.7
    container_name: meican-db
    volumes:
      - db-meican:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
  
volumes:
  db-meican: