name: Docker Compose only build

on:
  workflow_dispatch:
  push:
    branches:
     - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose -f "./docker-compose.yml" -f "./docker-compose.dev.yml" up --build
